name: Zahnarzt Dr. Stefan Bader
favicon: null
layout_spectrum: 0.28076112107373774
typography_spectrum: 0.9750269139185548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.712402255507186
  lightness: 0.6073823624756187
  saturation: 0.1870514159090817
  rhythmicContrast: 0.5386279881931841
purpose: []
