title: Zahnarzt Dr. Stefan Bader
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.179198
  brandStrength: 0.7293233
  lightness: 0.877193
  brandColors:
    - '#FFFFFF'
    - '#0564C8'
    - '#BBC2C9'
    - '#5B7281'
    - '#434241'
  rhythmicContrast: 0.00689223
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Zahnarzt Dr. Stefan Bader
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8972431
layout_spectrum: 0.5670426
